name: Backend Deployment

on:
  push:
    branches: [develop]

env:
  PROJECT_ID: fast-delivery-uma
  REGION: us-central1
  GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_CREDENTIALS }}"

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          project_id: fast-delivery-uma
          service_account: "staffysp5@gmail.com"
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Log in to Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: fast-delivery-uma
      - name: Use gcloud CLI
        run: |
          gcloud config set account github-actions@fast-delivery-uma.iam.gserviceaccount.com
          gcloud auth activate-service-account github-actions@fast-delivery-uma.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=fast-delivery-uma
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Build and push Docker image for backend
        run: |
          docker build -t us-east1-docker.pkg.dev/fast-delivery-uma/backend/backend ./fd-backend/
          docker push us-east1-docker.pkg.dev/fast-delivery-uma/backend/backend
